wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"
ota_password: "GENERATED_BY_THE_CONFIGURATION_SCRIPT"
fallback_ap_password: "GENERATED_BY_THE_CONFIGURATION_SCRIPT"
web_server_username: "admin"
web_server_password: "USE_A_UNIQUE_PASSWORD_OF_AT_LEAST_12_CHARACTERS"
